### ISSUE TITLE
Bungeecord option doesn't work

### ISSUE THREAD

**Issue by barcedev** [HyChrod/Friends2.0#1]
Installed the regular non-Bungeecord plugin onto my Hub server; no issues. Once I enabled 'bungeecord:' to true and installed the Bungeecord plugin onto the Bungeecord server, it no longer worked.

**Comment by Flo8433d** [comment]
You connected both plugins to the same mysql database successfully?

**Comment by Flo8433d** [comment]
New update available. Should work now

**Comment by HyChrod** [comment]
close

**Comment by HyChrod** [comment]
close #1
