### ISSUE TITLE
Feature Request: Change from "DisabledWorlds" to "EnabledWorlds"

### ISSUE THREAD

**Issue by altrisi** [HyChrod/Friends2.0#2]
I'm requesting the change of the config item "DisabledWorlds" to "EnabledWorlds" because there are lots of minigames servers without using BungeeCord, and that servers have lots of minigames worlds. Using "DisabledWorlds" I have to disable my >54 minigames worlds, and if I add more, I have to restart the server to add the new world. Changing it to "EnabledWorlds", I only have to put 9 worlds.

Thanks.

**Comment by Flo8433d** [comment]
Thanks for your suggestion. I will think about it and maybe add it in a future update
