### ISSUE TITLE
Jumping Probleme + Offline Nachrichten

### ISSUE THREAD

**Issue by TheDarkCookiee** [HyChrod/Friends2.0#3]
Manchmal wenn Spieler 1 zu Spieler 2 springt und dann wieder wechselt auf die Lobby ist bei Spieler 2 in der anderen Lobby noch die falsche Anzeige das also Spieler 1 laut dem Freunde System noch in der Nebenlobby steckt obwohl er auf der Hauptlobby ist.

http://prntscr.com/cvtqk4 Lobby wo Spieler 1 auf der Lobby ist

http://prntscr.com/cvtqyb Normal müsste da Lobby stehen aber da steht "yellowunity", also aktualisiert es sich nicht.

Logs sind dementsprechend nicht vorhanden

**Comment by TheDarkCookiee** [comment]
Edit:
Mir ist aufgefallen das auch die Nachrichten nicht funktionieren wenn wer online geht und offline.

**Comment by Flo8433d** [comment]
Werde mich darum kümmern

**Comment by Flo8433d** [comment]
Also ich habe mich mal ausgiebig mit dem von dir beschriebenen Problemen befasst, allerdings konnte ich nichts der gleiche Feststellen. Könnte es sein, dass eines der Plugins, auf einem der Server, Möglicherweise mit einer anderen MySQL Datenbank verbunden ist, oder eventuell sogar gar keine Verbindung herstellen kann?
