### ISSUE TITLE
BUG - cannot use commands in version 2.4.6-BETA

### ISSUE THREAD

**Issue by EUcreepemineCZ** [HyChrod/Friends2.0#5]
Hi, if I use any command in Friends 2.4.6-BETA, plugin write: an internal error occured while attempting to perform this command. I have server on Spigot 1.10-1.10.2. What can I do? Oldest version working, but this no.

**Comment by Flo8433d** [comment]
Check your Console and post your error

**Comment by EUcreepemineCZ** [comment]
> [2K [22:05:26 ERROR]: null 
> org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Friends2_0 v2.4.0-EXPERIMENTAL 
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-de459a2-51263e9] 
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-de459a2-51263e9] 
> at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-de459a2-51263e9] 
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101] 
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101] 
> at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-de459a2-51263e9] 
> at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-de459a2-51263e9] 
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101] 
> Caused by: java.lang.NullPointerException 
> at de.HyChrod.Friends.Friends.getString(Friends.java:154) ~[?:?] 
> at de.HyChrod.Friends.Commands.FriendCommands.onCommand(FriendCommands.java:79) ~[?:?] 
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-de459a2-51263e9] 
> ... 15 more

**Comment by Flo8433d** [comment]
You changed something wrong in your Messages.yml.
Please delete your Messages.yml and restart your server TWICE. It should work now

**Comment by EUcreepemineCZ** [comment]
very thanks! it work! very very thanks for help
