### ISSUE TITLE
problem with some nick (or UUID)

### ISSUE THREAD

**Issue by EUcreepemineCZ** [HyChrod/Friends2.0#7]
I have problem. I have in friends anyone, I don't him nick, I can't open GUI, because I have in /f list anyone, but his name is null and in .dat is UUID of him, but without nick in game. What can I do?

**Comment by Flo8433d** [comment]
Sorry but I cant understand your problem

**Comment by MinerLABSde** [comment]
Hallo ich bin toll!

**Comment by EUcreepemineCZ** [comment]
+HyChrod I have in my friends 4 players (in Utils.bat is 4 UUID), but in game I see 3 friends and in list is one null (friend, but don't exist), so I can't open GUI
