### ISSUE TITLE
[DE] GUI not works

### ISSUE THREAD

**Issue by Deminosa** [HyChrod/Friends2.0#8]
Hallo, Ich habe das Plugin auf unserem Netzwerk drauf aber das große problem das GUI geht nicht.

Kurzerkläreung was nicht geht:

► /f ()GUI Öffnent)
► Aufwählen von Option nicht möglich
► Nächste seite und zurück auch nicht
► Geblockte und Offene anfragen gehen aber zurück nicht und das annehmen und aufheben vom blocken auch nicht
► Jumup to friend nicht möglich (Bungeecord)

**Comment by Flo8433d** [comment]
Kommen denn Fehler in der Konsole? 
Die von dir beschriebenen Probleme, lassen sich für mich eigentlich nur durch ein fehlerhaftes editieren der Config- oder Messages.yml erklären. 
Macht ein Backup eurer Configs und versucht mal beide Dateien zu löschen und den Server zwei mal neuzustarten, um zu schauen, ob der Fehler an einer falschen Einstellung lag.

MfG HyChrod

**Comment by Deminosa** [comment]
Es kommt kein ERROR in der Spigot oder so.

Dennoch habseh ich grad das dass PL sagt das 2 Freunde noch online auf dem server wären, ob wohl die nicht drauf sind.

Config hatte ich mal komplett neu erstellen lassen so wie die Message.yml. und immer noch.

in Bungeecord kommt folgendes:

> 22:18:59 [INFORMATION] Changing item in slot 36 from Item@1509893126[amount=1, data=null, durability=0, meta=CraftItemMeta@872750275[listener=[]], tag={display:{Lore:[0:"öffnet ein Menü",],Name:"Menu",},}, type=345] to Item@219008848[amount=1, data=null, durability=0, meta=CraftItemMeta@348468913[listener=[]], tag={display:{Lore:[0:"öffnet ein Menü",],Name:"Menu",},}, type=345]
> 22:18:59 [INFORMATION] Changing item in slot 37 from Item@1375882545[amount=1, data=null, durability=3, meta=SkullMeta@849496753[p=GameProfile [id=74e96791-a805-46bf-9f86-0afc3aa66287, name=, properties=PropertyMap@308119543[properties={}], legacy=false], owner=null], tag={SkullOwner:{Id:"c3437fe9-9eff-4abc-bd1b-75e5cb58e25f",Properties:{textures:[0:{Signature:"O4PMgk9wa1Kynf9d3eRH3x5NG71cIYwOdMCWMRAXlLmNh+EmH+sYfpSQKeSNpWqX7lI13VRw2VTeFqdL9R/llmudDNUDqzMfH/xeA7ghDW1qsh6CgMbku8hIpjQ4iI2wDa3v13UJhJ4iyWsDOHmP/b7+FF2TT6ikQHcQSEcWZFm+JujFiJz7y4YrX1TU95wm77C4sZ48EPI97Ps2IwYMF2CpyJDx1hi4Dy0VoaHqf5AzWxKmNjwBfHz7EkTUgTeiA0psug6mBWmPds/r9TDKcVasxlR2OHJZy+pLvANSOX0VAyavpx3anFVLwG0fxHf+ud2iJuXVjtp6DP5SS/GKdFmZgGAnL8L4llL6sc/IDSY960Zgsmk1M1mUqf8LE6VX3rpfv4zec55+fbnNiFvU4IXrAK2NmlLhDGSVTz7VqScLrszKGEZOOLVas+YQFwDTyvzoIohuV3hvGBbs2PK1iqmV+ScNz6M9ig5oD9m1U9PhLHmp0H/4ceuLmISrTqpOh1KasQzmJm92Gwtcp239EbiRambEFEn68p6ABesHTLbEOZni1wQUB8BcSaWuIpFocKjGzLuQQmhjZYzGLXT8BjakbPu5uPUAm/ncWJy4vt39O1oK0qyTU43o6JxGQRz4FShNLOGbKs7p8C+k/LAx0LmCl6iuhaSGWTSpm46+u48=",Value:"eyJ0aW1lc3RhbXAiOjE0ODExNDkxMzYxMDYsInByb2ZpbGVJZCI6ImMzNDM3ZmU5OWVmZjRhYmNiZDFiNzVlNWNiNThlMjVmIiwicHJvZmlsZU5hbWUiOiJEZW1pbm9zYSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU3ODgxNDE5YTM0MmNkZjExZWIzMjM0ODRhNTY5NDkxZTAyNTM1MmFiM2JmNTAzN2M4M2VmNmZmNzkxNDNlIn19fQ==",},],},Name:"Deminosa",},display:{Lore:[0:"Rechtsklick um den GUI zu öffnen!",],Name:"Freunde",},}, type=397] to Item@286099490[amount=1, data=null, durability=3, meta=SkullMeta@1834882432[p=GameProfile [id=56d3ce46-35df-4266-9f2e-5142992fac18, name=, properties=PropertyMap@239738932[properties={}], legacy=false], owner=null], tag={SkullOwner:{Id:"c3437fe9-9eff-4abc-bd1b-75e5cb58e25f",Properties:{textures:[0:{Signature:"O4PMgk9wa1Kynf9d3eRH3x5NG71cIYwOdMCWMRAXlLmNh+EmH+sYfpSQKeSNpWqX7lI13VRw2VTeFqdL9R/llmudDNUDqzMfH/xeA7ghDW1qsh6CgMbku8hIpjQ4iI2wDa3v13UJhJ4iyWsDOHmP/b7+FF2TT6ikQHcQSEcWZFm+JujFiJz7y4YrX1TU95wm77C4sZ48EPI97Ps2IwYMF2CpyJDx1hi4Dy0VoaHqf5AzWxKmNjwBfHz7EkTUgTeiA0psug6mBWmPds/r9TDKcVasxlR2OHJZy+pLvANSOX0VAyavpx3anFVLwG0fxHf+ud2iJuXVjtp6DP5SS/GKdFmZgGAnL8L4llL6sc/IDSY960Zgsmk1M1mUqf8LE6VX3rpfv4zec55+fbnNiFvU4IXrAK2NmlLhDGSVTz7VqScLrszKGEZOOLVas+YQFwDTyvzoIohuV3hvGBbs2PK1iqmV+ScNz6M9ig5oD9m1U9PhLHmp0H/4ceuLmISrTqpOh1KasQzmJm92Gwtcp239EbiRambEFEn68p6ABesHTLbEOZni1wQUB8BcSaWuIpFocKjGzLuQQmhjZYzGLXT8BjakbPu5uPUAm/ncWJy4vt39O1oK0qyTU43o6JxGQRz4FShNLOGbKs7p8C+k/LAx0LmCl6iuhaSGWTSpm46+u48=",Value:"eyJ0aW1lc3RhbXAiOjE0ODExNDkxMzYxMDYsInByb2ZpbGVJZCI6ImMzNDM3ZmU5OWVmZjRhYmNiZDFiNzVlNWNiNThlMjVmIiwicHJvZmlsZU5hbWUiOiJEZW1pbm9zYSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU3ODgxNDE5YTM0MmNkZjExZWIzMjM0ODRhNTY5NDkxZTAyNTM1MmFiM2JmNTAzN2M4M2VmNmZmNzkxNDNlIn19fQ==",},],},Name:"Deminosa",},display:{Lore:[0:"Rechtsklick um den GUI zu öffnen!",],Name:"Freunde",},}, type=397]
> 22:18:59 [INFORMATION] Changing item in slot 38 from null to null
> 22:18:59 [INFORMATION] Changing item in slot 39 from null to null
> 22:18:59 [INFORMATION] Changing item in slot 40 from null to null
> 22:18:59 [INFORMATION] Changing item in slot 41 from null to null
> 22:18:59 [INFORMATION] Changing item in slot 42 from null to null
> 22:18:59 [INFORMATION] Changing item in slot 43 from Item@237134459[amount=1, data=null, durability=0, meta=CraftItemMeta@1317657931[listener=[]], tag={display:{Lore:[0:"Entscheide welche Spieler du sehen möchtest.",],Name:"Spieler verstecken",},}, type=369] to Item@864546802[amount=1, data=null, durability=0, meta=CraftItemMeta@1320561976[listener=[]], tag={display:{Lore:[0:"Entscheide welche Spieler du sehen möchtest.",],Name:"Spieler verstecken",},}, type=369]
> 22:18:59 [INFORMATION] Changing item in slot 44 from Item@1851711977[amount=1, data=null, durability=0, meta=CraftItemMeta@281194986[listener=[]], tag={display:{Lore:[0:"",1:"Geniesse deine Spielzeuge!",2:"",3:"",4:"Danke das du unseren Server supportest.",],Name:"Spielzeug",},}, type=357] to Item@1406784379[amount=1, data=null, durability=0, meta=CraftItemMeta@214766260[listener=[]], tag={display:{Lore:[0:"",1:"Geniesse deine Spielzeuge!",2:"",3:"",4:"Danke das du unseren Server supportest.",],Name:"Spielzeug",},}, type=357]
> 22:18:59 [INFORMATION] Changing item in slot 999 from null to null
> 

Ich hoffe das sie damit Eventuell was anfagnen können.
